### ISSUE TITLE
[Bug] Deprecated options is set in ServerSettingsProvider constructor

### ISSUE THREAD

**Issue by ulvesked** [Romakita/ts-express-decorators#195] opened 2017-12-20 12:14 UTC
## Informations

Type | Version
---|---
Bug | 2.18.2

****

## Description
In ServerSettingsProvider, endpointUrl and authentification options are deprecated and generate warnings each time server is started. 
These options should not be initialized by default, or the warnings should be disabled.

When building a console app, these warnings are always outputted to stderr on start.

## Todos

- [ ] Remove initialization of deprecated options in constructor

**Comment by Romakita** [comment] 2017-12-20 12:20
hi @ulvesked 

Is not a bug, the warning will be removed with the following PR https://github.com/Romakita/ts-express-decorators/pull/173
The PR will be released this month :)

See you,
Romain

**Closed** 2018-01-03 11:45 UTC
Labels: wontfix
